# ClockBot
ProxyPass /msnbc ws://localhost:39692/msnbc flushpackets=on
ProxyPassReverse /msnbc ws://localhost:39692/msnbc
<Location "/cmd">
  ProxyPass "http://localhost:39692/cmd"
  ProxyPassReverse "http://localhost:39692/cmd"
</Location>
<Directory "/httpd/waluigi_servebeer/html/page/soundboard/opodes">
  Header set Cache-Control max-age=86400
  <Files "boards.js">
    Header set Cache-Control max-age=600
  </Files>
</Directory>
