#!/bin/sh
rsync \
  --compress \
  --recursive \
  --include-from="./rsync-include.txt" \
  --exclude-from="./rsync-exclude.txt" \
  --delete \
  -e "ssh -i \"./notkeys/key\"" \
  ./ ubuntu@193.122.154.50:/var/www/
ssh -i "./notkeys/key" ubuntu@193.122.154.50 "curl localhost:39692"
echo "Done"
